---
name: NetBird Client
version: dev
slug: netbird_client
description: Radically simplify your network with a virtual networking layer that works the same everywhere -- NETBIRD
url: https://github.com/dannymate/netbird-client-hassio-addon
codenotary: codenotary@frenck.dev
startup: services
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  9993/tcp: 9993
ports_description:
  9993/tcp: ZeroTier's primary port
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
devices:
  - /dev/net/tun
map:
  - ssl:rw
options:
  NB_MANAGEMENT_URL: "" 
  NB_SETUP_KEY: ""
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
